### ISSUE TITLE
knife-artifactory unshare doesn't seem to work

### ISSUE THREAD

**Issue by ghost** [JFrogDev/knife-art#2] opened 2017-04-07 01:38 UTC
When I try to use `knife-artifactory unshare` I get an error, even though I have delete rights (and share works for my user).

Here's what it looks like when I run the command with an artifactory 5.1.0 server:

```
knife artifactory unshare mycookbook 0.1.0
Are you sure you want to delete version 0.1.0 of the cookbook mycookbook from Artifactory? (Y/N) Y
ERROR: The data in your request was invalid
Response:
```

I expect not to see this error.

**Comment by 85danf** [comment] 2017-04-26 08:01
Hi there and thanks for reporting this,

Can you please post the what the Artifactory log shows when you run the command?
Also, when posting errors from the client please use the verbose flag (-V) and post the entire output from the client as well.

Thanks.

**Comment by ghost** [comment] 2017-04-27 21:26
-V output:

```
$ knife artifactory unshare mycookbook 0.1.0 -V
INFO: Using configuration from /Users/myuser/.chef/knife.rb
Are you sure you want to delete version 0.1.0 of the cookbook mycookbook from Artifactory? (Y/N) Y
INFO: HTTP Request Returned 400 Bad Request:
ERROR: The data in your request was invalid
Response:
```

**Comment by ghost** [comment] 2017-04-27 21:31
artifactory log (and yes I've set a default deployment repository on the virtual repo):

```
2017-04-27 14:24:38,284 [http-nio-8081-exec-4] [ERROR] (o.j.r.c.u.ChefUtils :65) - An error occurred while handling a Cookbook request: Cannot delete cookbook version from virtual repository
```

**Comment by 85danf** [comment] 2017-06-04 15:22
ok, so unfortunately undeploy from virtual repos is not supported - that's why its failing for you.
It's like this by design and for a good reason --> undeploy from a virtual when a user does not know what is the default deployment repo (that info is not available to non-admins) may produce unwanted behavior (i.e. user expects it to be removed from entire virtual while it was only removed from the deployment repo).

You are more than welcome to submit a feature request via our support [portal](https://support.jfrog.com/) - I'm closing this issue as this is an Artifactory issue and not directly related to the plugin.

**Closed as completed by 85danf** 2017-06-04 15:22 UTC
